### ISSUE TITLE
Persistantly reoccurring patchbay connection

### ISSUE THREAD

**Issue by mbutz** [falkTX/Carla#1032]
I have the following patchbay setup stored in a `*.carxp` file:

![carla-01](https://user-images.githubusercontent.com/3934249/75167113-31da0680-5725-11ea-9428-046b082d67b7.png)

Any time I load this setup I get a connection from `SuperCollider 1/2` to `system` (which is not what I want).

![carla-02](https://user-images.githubusercontent.com/3934249/75167381-8ed5bc80-5725-11ea-85c2-728b0fbb5300.png)

Removing this connection and storing the file according to the first image does not help.

So more generally: Carla seems to make a default connection for channel 1 and 2 irrespective of what has been stored previously. Or am I wrong?

**Comment by falkTX** [comment]
Do you have ladish running?

**Comment by mbutz** [comment]
Nope. Should I?

**Comment by falkTX** [comment]
No, it is just the usual culprit in these cases.

Might be you just need to save the carla project again after you disconnect those 2 ports.
Carla, when running outside of session managers, will keep save and restore jack connections.

**Comment by mbutz** [comment]
> Might be you just need to save the carla project again after you disconnect those 2 ports.

I did this several times but as far as I see it is reproducable that this (and only this) change will not be stored. Is it possible, that this has something to do with the fact that my SuperCollider application (which is Sonic Pi) considers port 1 and 2 as default ports?

**Comment by falkTX** [comment]
sorry for late response.
I believe that is indeed correct, super collider will just connect to the default output ports in order to provide sound "out of the box". perhaps there is a CLI switch to disable that behaviour?

carla will only save and restore connections in a way that it will actually connect new things.
it will never disconnect ports when loading a project.

as far as I can see, this is an issue with supercollider.

note: jack2 has a engine setting/option to restrict self-connections, might be useful here.

**Comment by mbutz** [comment]
Ok. That explains it. Thanks a lot for the feedback!
