### ISSUE TITLE
Can't install carla nor carla-git in debian bullseye

### ISSUE THREAD

**Issue by rbino** [falkTX/Carla#1055]
Hi,
following the [removal of qt4 from debian bullseye](https://wiki.debian.org/Qt4Removal), the `carla` and `carla-git` can't be installed from KXStudio repos.
```
$ sudo apt install carla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 carla : Depends: libqtcore4 (>= 4:4.5.3) but it is not installable
         Depends: libqtgui4 (>= 4:4.6.1) but it is not installable
         Recommends: python3-rdflib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
```
$ sudo apt install carla-git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 carla-git : Depends: libqtcore4 (>= 4:4.5.3) but it is not installable
             Depends: libqtgui4 (>= 4:4.6.1) but it is not installable
             Recommends: python3-rdflib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Is there a workaround? Is it possible to make libqtcore4 optional for `carla-git` (IIRC it shoulde be Qt5 based)?

**Comment by syboxez** [comment]
You can recompile the package after editing the proper files in debian/ to remove the Qt4 dependencies. Be sure to compile with the makeflag "HAVE_QT4=false", and be sure to include paths for moc-qt5, rcc-qt5, and uic-qt5. For example, you make command should look like this:

make HAVE_QT4=false MOC_QT5=/usr/bin/moc-qt5 RCC_QT5=/usr/bin/rcc-qt5 UIC_QT5=/usr/bin/uic-qt5

**Comment by jcafhe** [comment]
Hi, I've run into the same issue for quite a time. Following @syboxez's advices, I've managed to get carla installed (didn't try with carla-git). Here are the steps I've done, following  [debian wiki](https://wiki.debian.org/BuildingAPackage) too. Please keep in mind that I know almost nothing about debian packaging, so that should not be the optimal way:

- First you need the **mk-build-deps** tool contained in devtools package.
- create a source working directory (e.g. `~/swd/`).
- **download the carla source** (don't need to be su) in the working directory:
`apt source carla`
  So now you should have a carla source directory, something like:
 `~/swd/carla-2.0.0+git20190808.3/`

- **edit the *control* file** in `~/swd/carla-source-dir/debian/` and remove *"libqt4-dev"* in *"Build-Depends"* list.

- **download and install build dependencies from the control file**. Assuming that your are in carla-directory:
`sudo mk-build-deps -i debian/control`
This should create a single package named "carla-build-deps", so you can easily remove all deps at once:
```
apt info carla-build-deps
Package: carla-build-deps
Version: 5:2.0.0+git20190808.3
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 9 216 B
Depends: build-essential:amd64, debhelper (>= 8), pkg-config, pyqt5-dev-tools, qtbase5-dev, qtbase5-dev-tools, libgtk2.0-dev, libgtk-3-dev, libasound2-dev, libpulse-dev, libmagic-dev, libx11-dev, libgl1-mesa-dev | libgl-dev, libglu1-mesa-dev | libglu-dev, liblo-static, fftw3-static, mxml-static, zlib-static, ntk-static, fluidsynth-static
Conflicts: glib-static, libffi-static, libfftw3-dev, libfluidsynth-dev, liblo-dev, libmxml-dev
Download-Size: inconnu
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: build-dependencies for carla
 Dependency package to build the 'carla' package
```

- **build carla**.Assuming that your are in carla-directory:
`fakeroot debian/rules binary`

- **Install the .deb files** which have been created in `~/swd/`, first *carla-data*, then *carla* :
`sudo apt install ./carla-data_2.0.0+git20190808.3_all.deb`
`sudo apt install ./carla_2.0.0+git20190808.3_amd64.deb`

The build process reports the following:

```
 ---> Main features 
Front-End:     YES (Using Qt5)
LV2 plugin:    YES
VST plugin:    YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST:      YES (with UI)

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      NO  [Qt4 missing]
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: YES

---> External plugins: 
DPF Plugins:  YES (with UI)
DPF ProM:     NO  [missing libprojectM]
ZynAddSubFX:  YES (with NTK UI)
```

**Comment by falkTX** [comment]
I am pushing a build to the kxstudio repositories that removes qt4 as runtime dependency, making it optional.

**Comment by rbino** [comment]
@falkTX thanks, let me know when it's in the repo so I can test and confirm that it's possible to install it again

**Comment by falkTX** [comment]
alright, should work now, please confirm :)

**Comment by nthhhhhhh** [comment]
@falkTX 
Working for me when it previously was not, thanks.

$lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye

**Comment by falkTX** [comment]
Thanks, will close this one then

**Comment by rbino** [comment]
Yes I confirm it's working now.

Thanks a lot!
