### ISSUE TITLE
How to select specific PulseAudio input?

### ISSUE THREAD

**Issue by OnkelTem** [falkTX/Carla#1066]
I want to add a noise filter as a middleware for my external USB microphone. 
The system is: Kubuntu 18.04

This is how I configured Carla:

1. Engine is set to PulseAudio:

![](https://i.gyazo.com/3591ee22996ada2c311a776e5c9f8051.png)

2. and this is its settings:

![](https://i.gyazo.com/d9b2295b9db60635c56adc474b6eb9a1.png)

3. Patchbay routing view:

![](https://i.gyazo.com/fbe36175add8e73f4ff22d05b406c98b.png)

My problem is that I cannot select/change an input provided by PulseAudio. I cannot find any place where it's configured. 

It seems like the **Audio Input** device is picking the first/random input from PA. 

I know I can configure it at the PA's side, but I want to come up with some **persistent configuration** which is not spread out over several unconnected entities.

**Comment by moonshaadow** [comment]
Is your usb mic correctly recognized by linux ? Maybe you should use JACK or alsa driver instead of PA, for a better experience. Anyway, **pavucontrol** help you to manage PA in and out, but I'm not sure if it is highly configurable... 
If you have no choice to use PA, consider to use Cadence, which manages and bridges very well JACK, alsa and PA together.

**Comment by OnkelTem** [comment]
@moonshaadow, yes my usb mic is good, but there can be more than one input, so the problem is how to pick the right one. But thanks, I'm gonna try to Cadence then. Also I came across `pacmd` utility which is a command line PA configuration tool. Haven't learned to use it yet though..

**Comment by falkTX** [comment]
Carla cannot use pulseaudio in the same way it uses JACK, it cannot stay in the middle between arbitrary inputs and outputs.
JACK is the exception here, since it is something I use on a daily bases, Carla has special support for it. multi-client is JACK only, and will remain that way.
Thanks for understanding.
