### ISSUE TITLE
HiDPI - Carla scales but plugins do not

### ISSUE THREAD

**Issue by agaskins** [falkTX/Carla#1121]
I realize this isn't a direct issue with Carla per se, but is there any way to scale plugins to appear properly on HiDPI displays? I believe Reaper 6 has incorporated such a feature, but I haven't tested it. Is this just outside of the scope of Carla, or a feature that might be possible (or available already, and I'm just not finding it)?

If this is irrelevant to Carla all together, does anyone have a way to deal with this issue short of lowering resolution to 1080?

I apologize if this is not the appropriate place to ask this. I didn't know where else to post.

![Screenshot from 2020-05-05 18-51-22](https://user-images.githubusercontent.com/5066354/81123597-73471900-8f01-11ea-96da-72c5cc6cad69.png)

**Comment by falkTX** [comment]
I do not have a high-dpi screen myself, and their usefulness aside, scaling will depend on the plugin implementing the proper things to figure out what it needs to use.
For LV2, carla passes "lv2ui:scale" as a property, the same could be done for VST but I need to find a plugin that implements this first.
Pushing the issue to surge might be the best case here, since that plugin is opensource and also supports LV2. so we can easily tweak it until it behaves properly.

Note that while I can add the support for such screens, I cannot test it myself.
So I rely on you and others to do that for me.

**Comment by falkTX** [comment]
Submitted a patch to surge at https://github.com/surge-synthesizer/surge/pull/1851

Would be really awesome if you could try it.
If you need assistance getting a binary, let me know.

**Comment by falkTX** [comment]
any news on this? were you able to test?

**Comment by agaskins** [comment]
Had surgery and just now getting back to all this. I'm really sorry!

This is by far the most amazing response I've had to an issue haha. I'd love to test this but the nightly package is a deb file - I'm on Arch.

I'll try building from git, but just wanted to check that this patch is in master branch?

**Comment by falkTX** [comment]
No need to be sorry. We can go on a plugin-by-plugin basis.
Thanks for confirming the fix!
