### ISSUE TITLE
Export to LV2 only supports saving to default LV2 path

### ISSUE THREAD

**Issue by aqxa1** [falkTX/Carla#1172]
As title, when exporting a plugin to LV2, only the default path can be selected. This path tends to be a non-user writable path (/usr/lib/lv2 by default), so it's not possible to save the exported plugin without being the root user, on Linux at least.

EDIT: Changing [this line](https://github.com/falkTX/Carla/blob/62f27b046d62628d8769ee1a9afe53310514b65c/source/frontend/carla_skin.py#L1271) from editable=False to editable=True works around the problem (allowing you to manually edit the path) although I feel it should be a dropdown list of paths as set in the GUI.

**Comment by falkTX** [comment]
I made it that way so that after creating the plugin it can actually be found and loaded by other hosts.
Not everyone understands that LV2_PATH env var is a thing.

The issue here that I see is actually that, if ~/.lv2/ does not exist, carla does not offer the option to save in there.
But ~/.lv2/ should be the default path to save to.

**Comment by falkTX** [comment]
Actually no, I am wrong. Carla does create ~/.lv2/ if needed.
So I guess your LV2_PATH does not include it, and thus carla does not show it.
Please confirm.

**Comment by falkTX** [comment]
ping :)

**Comment by aqxa1** [comment]
Hi, sorry this slipped my mind.

And yeah, my LV2_PATH doesn't include ~/.lv2. However, it seems that LV2_PATH is now working for me, and I can also set multiple paths by separating with ':'. It would be nice to be able to set additional paths from the GUI, and maybe a warning about permissions, but at least it works.

I'm not sure why it wasn't working before, but there you go.

**Comment by falkTX** [comment]
ok great. I am not very keen on adding custom paths, as that would go against the LV2 specs a bit.
https://lv2plug.in/pages/filesystem-hierarchy-standard.html

Hiding the non-writable paths is something I will skip for now.
There is no loss in user data when the user chooses that folder, since the lv2-export dialog has no other input but the path.
So when that errors out, the user can simply go back and pick a different folder.

**Comment by aqxa1** [comment]
Since I ran into the problem again, the issue seems to be that `LV2_PATH` and the folders that you can set in Settings -> Plugin Paths -> LV2 would be expected from the user perspective to be synchronised, but they are not (i.e. `LV2_PATH` should equal all paths listed in the GUI). Perhaps the plugin paths are exclusively for reading rather than writing, but it's a bit unclear. Maybe a note that writable locations can only by set with LV2_PATH could be added, if it's not possible to update the env from within Carla.
