### ISSUE TITLE
Problem dragging a .carxp from sidebar to canvas

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1178]
![image](https://user-images.githubusercontent.com/108225/85214495-6e301300-b363-11ea-8549-64eb7c3e8691.png)

**Comment by falkTX** [comment]
is this under session management?

**Comment by mxmilkiib** [comment]
Yes.

**Comment by mxmilkiib** [comment]
Actually, I think I can reproduce this with no sm. Possibly there might also be a problem with dragging a project file onto the canvas twice.

**Comment by falkTX** [comment]
I think I see what this is.
You are loading a project made with carla <2.2, which did not save the connections in the project file.

As a workaround, you can load this specific project with carla standalone (which will use the extra json file for canvas positions in backwards-compat mode) and then just save the project.
The next time you drag&drop the project, canvas positions should load properly.

Since in 2.1 canvas positions were only saved and restored in standalone mode, I consider this to not be a regression.

If you find issues regarding saving and restoring connections with the new version (git/develop branch) then I will for sure pay attention to it. But not so much when it comes to loading old stuff.

**Comment by mxmilkiib** [comment]
```
<milkii> ... i've just tried dragging a .carxp from the sidebar to the patchbay, one that was saved outside of a sm, and i'm still getting the everything-in-the-save-gets-added-but-positioned-in-a-column-and-with-no-connections
<falktx> milkii: is there a ticket for this already open? can you mention it there
```

**Comment by falkTX** [comment]
This was fixed just now.
I have a plugin here that does not consistently restore its position though, so investigating that atm
