### ISSUE TITLE
--cnprefix and nsm?

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1192]
Is there some way --cnprefix could become usable with NSM (given NSM doesn't take arguments)?

**Comment by falkTX** [comment]
not really, it is up to the NSM server to give the provide the client name prefix.

**Comment by falkTX** [comment]
For personal use, you can create a shell script that just starts up carla-jack-multi with a custom client name prefix.
Not sure if that really works though, Carla likely will want to use the client prefix supplied by NSM.

Need to say that this is just unsupported. Mostly due to restrictions on NSM side
