### ISSUE TITLE
Carla-control : wrong OSC adress when 2 instances of Carla

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1252]
- Open Carla (carla 1), load a plugin, open Carla-control, connect.
- open another carla (carla 2), load a plugin, open another carla-control and connect it to carla 2.

carla-control 2 doesn't correctly control carla 2, sending an osc message on incorrect adress : 
`CarlaEngineOsc::handleMessage() - message not for this client -> '/Carla/0/set_active' != '/Carla_01/'`

**Comment by falkTX** [comment]
these 2 different carla instances each have their own unique OSC port, right?

**Comment by moonshaadow** [comment]
Yes.

**Comment by falkTX** [comment]
Now fixed in latest develop/git

**Comment by zigmhount** [comment]
Hi, sorry to revive a 5-years old thread, was this ever merged into release? I seem to have the same issue on Carla 2.5.9: I start 2 instances of carla-jack-single on a remote machine with `CARLA_OSC_UDP_PORT=11080` and `CARLA_OSC_UDP_PORT=11070` (I tried also to set the TCP ports for both instances); OSC messages work fine with the first instance, but for the second instance I'm getting the same message as above:
```
[carla] CarlaEngineOsc::handleMessage() - message not for this client -> '/Carla/0/set_parameter_value' != '/Carla_76/'
```
The main problem is that the number behind `Carla_` change at each session, and since it's a remote machine that expects to set up the OSC connections automatically, it's quite a problem.
Is there a development branch in this repo that I may use instead of the official 2.5.9?
