### ISSUE TITLE
Linux-VST3 support not available on pre-built/official binaries

### ISSUE THREAD

**Issue by shivpalkang** [falkTX/Carla#1266]
I am running Carla 2.2.-RC-2 on Ubuntu Studio 20.04, downloaded from https://kx.studio/Downloads
When I scan for Linux native VST3 plugins it spits out this error:
> carla-discovery::error::VST3 support not available

I found out from https://kx.studio/News/?action=view&url=carla-22-rc1-is-here that Linux Native VST3 plugins were now supported and
>Worth noting is that this is not a custom implementation, but leveraging JUCE VST3 host support on Linux.

I complied the JUCE AudioPluginHost separately, and it runs fine as an executable, do I need to link it to Carla somehow? Or am I completely missing a point somewhere?

**Comment by falkTX** [comment]
bad news. I am using GCC4 in the official builds in order to get some nice backwards-compatible binaries.
even though I can fix JUCE to be GCC4 compatible, the VST3 SDK internals heavily rely on features that are not compatible with old systems.

I do not want to bump the requirements of the pre-built linux binaries just yet, so for now these builds will not have VST3 support (for linux-native plugins)

**Comment by shivpalkang** [comment]
Oh okay, thanks for the response. So, will the Linux-VST3 support work if I compile Carla from source using the latest VSD3-SDK and GCC9.3?

**Comment by falkTX** [comment]
You do not need vst3sdk yourself since it is pre-included in carla.
But yes, self-builds of carla will have everything. check `make features` before building to see if anything is missing. (ignoring external plugins)

**Comment by shivpalkang** [comment]
Cool! Thanks mate. I'll check it out.

**Comment by falkTX** [comment]
I am closing this ticket due to temporarily not making linux binary builds.
It is going to take a while to get proper linux builds back, need to setup a few things and make sure it is automated (so I dont need to run things manually anymore, too much time wasted...)
