### ISSUE TITLE
Carla crashes under NSM saving LV2 Convolution with impulse

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#1280]
On last release 2.2.0

Carla crashes under NSM when I add LV2 convolution plugin, setup a convolution .wav file and save the session.
(Joys of nsmd make the session impossible to close because an operation pending ('save the session' here), but this is another subject).

This only happens if there is no attribute IgnoreClientPrefix='true' in the .carxp file.

If this attribute is true, something weird is the path for the convolution file. The file (which is a symlink) is saved in the session folder, in a subfolder name 'Carla', or 'Carla01' or upper. This should be saved in a folder starting with the path given by the NSM server !! How could multiple instances know which folder is their one ?

This is probably linked to #1279.

**Comment by Houston4444** [comment]
I really think that theses two bugs are important because I don't see how to resolve them without problems with backward compatibility (#1279 and this one). I would be happy to try fix them but first, I'd like to understand what you tried to do (or probably what is supposed to work somewhere but not on my machine) with NSM jack client id.

Reading one more time the NSM API, I see that symlinks can be saved in another dir than client path in the session(I must say I don't like this idea). However, if choice is to not use the client path, why not use the same folder for all instances ? Here it doesn't works, because an instance started the first at last save won't find its files if it is started the second (and reversely).

**Comment by falkTX** [comment]
This was a result of 2 independent issues.
1st, Carla was not registering the "main" client under multi-client mode with the needed prefix. So we got carla and carla-01 etc behind the scenes. JACK assigning carla-01 as name to carla made it confused, and the client prefix handling fails.
A quick solution is to use the full client name provided by NSM in multi-client mode. This client is not really seen by users, so the name is not important visually, but it is important to be consistent.

2nd, carla was setting the folder to save files to AFTER saving, not BEFORE. leading to plugins saving in the wrong locations.

Both are fixed now as far as I can tell.
There will be issues if carla is started both inside and outside NSM, but that would involve a deeper, more involved fix that doesnt give me enough time for the April 15th release.

If this issue comes up again, let me know. Otherwise assumed fixed.

**Comment by Houston4444** [comment]
Yes, It works better, thanks !

I wonder why the data folder for links is `${client_name}_${client_id}` and not directly the path given by NSM server `${client_name}.{$client_id}`. Not very strong, but it breaks RaySession client template process (RS recognizes with given pattern which file belongs to which client to make a client template). This is very useful when user wants to start many times the same set of plugins with the same config in a new session. Of course, I can workaround this easily modifying the client template process, but I wonder if there is a good reason for that folder choice, I haven't seen Carla use this folder (`${client_name}.{$client_id}` given by server) for anything else.
