### ISSUE TITLE
Calf Vocoder plug in has no Filter analyser 

### ISSUE THREAD

**Issue by mrEmpire44** [falkTX/Carla#1322]
When calf vocoder is in carla, there is no filters analyser 

Seems to be for the case for the latest version of calf and earlier versions.

https://imgur.com/Cq0XChG.png

using patchbay mode. Latest version of carla.

**Comment by falkTX** [comment]
This is expected and not a bug.
Carla runs plugin UIs in a separate process in order to prevent UI related crashes to take down Carla.
Since Calf UI uses Gtk2 and Carla UI uses Qt5, it can certainly have weird, random side-effects.

You can disable the UI bridges in the carla engine options if you wish.
