### ISSUE TITLE
carla-discovery::error::Not a LADSPA plugin - /usr/lib64/ladspa/calf.so

### ISSUE THREAD

**Issue by martinkg** [falkTX/Carla#1404]
Hi,

when i install ladspa-calf-plugins-0.90.3 on Fedora34, Carla will not list the plugin although the library path is present. 

installed Version:
Carla-2.3.0-1.fc34.x86_64
ladspa-calf-plugins-0.90.3-8.fc34.x86_64

The log file prints the error:
carla-discovery::error::Not a LADSPA plugin - /usr/lib64/ladspa/calf.so

Regards
Martin

**Comment by falkTX** [comment]
I really suspect that is not an error.
Likely the plugin does not expose the needed symbol to be a ladspa plugin.
It needs to have `ladspa_descriptor`.

For example:
```
$ objdump -T /usr/lib/ladspa/3BandEQ-ladspa.so  | grep ladspa
/usr/lib/ladspa/3BandEQ-ladspa.so:     file format elf64-x86-64
0000000000005070 g    DF .text  0000000000000014  Base        ladspa_descriptor
```

Also.. please stop using calf as ladspa. loading that together with calf lv2 will result in a crash.
Upstream calf has dropped ladspa support for many years now.

**Comment by ferdnyc** [comment]
I've determined that the Fedora calf build no longer includes LADSPA compatibility, as you surmised @falkTX. The `ladspa-calf-plugins` symlink (that's all it was) to `calf.so` was just a misleading leftover from the time when the calf shared lib _was_ LADSPA-compatible. That time ended in 2016, best I can figure.

Fedora's going to drop `ladspa-calf-plugins` so that it'll no longer be advertised with a capability it doesn't have. (See [RHBZ#2064061](https://bugzilla.redhat.com/show_bug.cgi?id=2064061).) This can probably be closed.

**Comment by falkTX** [comment]
Kinda expected, thanks. Will close this one
