### ISSUE TITLE
Calf X-Over Plugin is missing GUI elements

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [falkTX/Carla#1632]
When I add a calf x-over plugin to my carla board, I cannot change the divider frequency and no audio is passing through. The calf plugin looks correct when loaded in Calf Jack Host.

For comparison:

In carla (missing the graph):
![image](https://user-images.githubusercontent.com/10342708/176020572-adf65163-4aa3-413e-8f86-1c5fc591d413.png)

In Calf Jack Host (looks good and works):
![image](https://user-images.githubusercontent.com/10342708/176020313-a754fe1d-ef17-4b6c-a388-1b52be950d6d.png)

How can I make the plugin look the same as in calf jack host? Most other plugins I tried so far look good and work normal in carla.

**Comment by 0xFEEDC0DE64** [comment]
Correction: the plugin also produces the correct effect in carla, I had an error in my audio setup, so just the missing graph is all I'm asking for :)

**Comment by galileo-pkm** [comment]
Same issue with other plugins like equalizer.

**Comment by falkTX** [comment]
this is normal and expected. these UIs are running on a separate process as a way to not get crashes if they do bad things (also as protection against running gtk2 stuff on the main process).
you can uncheck the option to use UI bridges under carla engine settings, save and reload the session and then you will see the fancy calf graphs.

but... if things crash dont come complaining.
specially important if carla (due to qt) ends up using gtk3 functionality (to provide native desktop file browser, for example) which will conflict with calf's gtk2 usage.

the solution is for plugin UIs to not use gtk, that has always been a bad decision. but too late for that now..

**Comment by galileo-pkm** [comment]
> this is normal and expected. these UIs are running on a separate process as a way to not get crashes if they do bad things (also as protection against running gtk2 stuff on the main process). you can uncheck the option to use UI bridges under carla engine settings, save and reload the session and then you will see the fancy calf graphs.

Unless I'm missing something I already have that enabled and the issue persists. 

![image](https://user-images.githubusercontent.com/8114900/195675179-d56c4dc5-621f-4248-bbec-ea2515bc8bf2.png)

**Comment by galileo-pkm** [comment]
Thanks, unchecking (misread the first time) solves the issue.
