### ISSUE TITLE
carla 2.4.3 error  "Juce-based plugin not available"

### ISSUE THREAD

**Issue by A350** [falkTX/Carla#1781]
I use Carla 2.4.3 and Wine 7.0 in Debian 10.. but with some update.. the plugins .dll are not loading.

I receive the error from "Juce-based plugin not available"

**Comment by lacedemonio666** [comment]
The same thing, I use Carla 2.6.0 in Ubuntu 18.04

**Comment by A350** [comment]
> Ubuntu 18.04

2.6.0 ? what ? the last version is 2.5.5

**Comment by falkTX** [comment]
my bad, pushed something to latest git that is missing a few pieces.
will try to push a fix for it tomorrow.

for now you can export `CARLA_DO_NOT_USE_JUCE_FOR_VST2` and `CARLA_DO_NOT_USE_JUCE_FOR_VST3` to any value and start carla from that terminal.

this is basically due to me removing the use of juce when plugin bridges are in play.

**Comment by A350** [comment]
uff.. OK.. waiting..  =)

**Comment by lacedemonio666** [comment]
I think is a 2.6.0 alpha version in ubuntu 18.04 (carla-git), the add plugin function still closes with the new update, but it seems that they can now be loaded plugins with the file browser.

**Comment by A350** [comment]
OK.. updated, working again, thanks !

**Comment by falkTX** [comment]
thanks for confirming! closing the issue then
