### ISSUE TITLE
all carla plugins appear as instruments in renoise

### ISSUE THREAD

**Issue by spectromas** [falkTX/Carla#189]
The carla vst plugins are only showing up in renoise as instruments (as opposed to effects and instruments). This is with an up to date pull of carla and renoise 3.0.1.

**Comment by falkTX** [comment]
I can't confirm this. The plugins appear as fx+synth as expected here.

Can you re-test this?

**Comment by spectromas** [comment]
I removed the CachedVSTs and CachedFailedVSTs files in ~/.renoise and rescanned and sure enough they are showing as expected now. Not sure what could have happened but I'm sorry to waste your time and thank you!

**Comment by falkTX** [comment]
Alright, thanks!

I'm not sure if I'll change the vst plugins or not.
Each plugin is now separate, and being a bit big (~15Mb) wastes space.

I could do them as vst-shells so that 1 *.so file provides all plugins.
Most hosts support this (energyXT doesn't).

It will break old saves, but Carla2 is in beta...

**Comment by spectromas** [comment]
Sounds like it might be more efficient and streamlined that way then but wider compatibility is perhaps something to weigh against that?
