### ISSUE TITLE
calf analyzer plot doesn't show

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#247]
when i open calf eq or calf analyzer the plot doesn't appear. running carla 1.9.5~git20150423.2 with calf-plugins 1:0.0.60-1kxstudio1

**Comment by falkTX** [comment]
known "issue", the calf plots only appear when UIs are not running as bridges.
uncheck the "direct handling of UI..." in the carla engine options to see them.
if calf crashes for some reason it will bring down carla too though.

**Comment by zettberlin** [comment]
I tried this (uncheck UI-bridged) but still there is no plot in CALF.
BTW: the animated plots worked perfectly in older versions of CALF without switching off bridged mode.

**Comment by falkTX** [comment]
I've discuss this several times now.

Calf UIs need instance access (non-bridge mode) in order to show their graphs.
But this is not 100% safe, so it's disabled by default in Carla now.

If you have previous projects with calf plugins on them you might need to open the settings and re-save.

I'm going to do a small change in the calf code to make show the Analyzer always works.

**Comment by zettberlin** [comment]
Now I got a different result, while unchecking PreferUiBridges did *not* yield the plots, they now appeare after I set the opition manually in .config/falkTX/Carla2.conf

Thats my setting:

[Engine]
AudioDriver=JACK
ProcessMode=1
ForceStereo=false
PreferPluginBridges=false
PreferUiBridges=false
UIsAlwaysOnTop=false
MaxParameters=200
UiBridgesTimeout=4000

Now it does work as expected but anyway: the plots where in der plugins 2 weeks ago with an older Calf build. Could it be, that this older versions of Calf simply refused to use the bridge and Carla refrained gracefully?

**Comment by falkTX** [comment]
> Now it does work as expected but anyway: the plots where in der plugins 2 weeks ago with an older Calf build. Could it be, that this older versions of Calf simply refused to use the bridge and Carla refrained gracefully?
No.
Carla is the one that manages the UI, not the plugin.

As I said if you have the calf plugins in a saved project the carla's global settings will be ignored.

Anyway, this is sorta an issue with calf, not carla.
LV2 instance-access is not a good thing to use, specially if the UIs use system toolkits (gtk2 in calf's case).
I'll patch calf to make sure the analyzer always shows the graph, because the plugin is useless otherwise.
For all other UIs they will not show graphs by default in Carla.

**Comment by rhetr** [comment]
it's too bad, i've had calf crash on me numerous times under carla when i've enabled instance-access.. do you know if calf ever plans to move away from instance-access?

**Comment by falkTX** [comment]
I've talked with them a little, they plan to move some UIs to atom messages.
But it might take a while.
