### ISSUE TITLE
Lv2 and internal plugins do not load in Carla-lmms

### ISSUE THREAD

**Issue by faraway1nspace** [falkTX/Carla#273]
Hello and thanks a lot for Carla!

Lv2 and internal plugins do not load in Carla-lmms Rack or Patchbay (I tried Zasf internal, Drmr, amsynth-lv2, calf effects, Wolpertinger, etc). No sound is produced. The plugin names show up in the Carla add-plugin pop-up, but then nothing happens when I try to add them.  The DSSI, VSTs, and LADSPA plugins all load and perform as expected, however, trying to remove them creates another weird issue: when I try to remove, the plugins disappear from the Carla-rack tab, but their icons remain on the patchbay canvas, until I close and re-open the carla-lmms GUI.

Old saved LMMS projects that already had carla-rack/patchbay loaded with lv2 plugins still have the plugins loaded and produce sound, but I cannot add new lv2 plugins. The lv2s and intervals plugins still load as expected under Carla-standalone. I am using Carla version 1.9.6 (2.0-beta4) on Ubuntu 14.04, using binaries from the Kxstudio repos.

Thanks again for this great project!
Rob

**Comment by falkTX** [comment]
you are right.

one of the commits I did recently broke carla as a plugin.
I need to fix this..

**Comment by faraway1nspace** [comment]
Great! The latest update solved it. Thanks.

**Comment by farvardin** [comment]
Hello, I don't know if it's related, if it's not I can open a new issue, but I'm using Carla baypatch in LMMS (1.1.3 or 1.2). It works rather OK, but sometimes some instruments in the carla plugin (lv2) are not correctly saved. I'd say 1/10 of them has this problem (most are saved ok). After reloading the song, we notice some settings in the instruments are different from what they were before saving them, so it sounds odd (for example in a FM instrument, the algorithm used will be the 1st instead of the 15th). But, if I open again the carla baypatch rack, clic on the option button to load the LV2 interface, then select the instrument again, it will reload correctly into the song. It's a bit tedious to do this for every instrument in a song, but it works at least... 

So it worked like this until the latest carla and dexed updates from kxstudio (2017-08-28 and 2017-08-26). Now when loading a song, all instruments are muted. If like before I open the carla rack, and reload manually every instrument, it worked. Then I've upgrade LMMS to latest git version (yesterday's date), and now when I click in a carla instrument, it just crashes LMMS. :(
