### ISSUE TITLE
Carla Parameter CCs maximum

### ISSUE THREAD

**Issue by sonejostudios** [falkTX/Carla#277]
..is 95 instead of 127.

**Comment by falkTX** [comment]
the maximum should be 120, not 127.
CCs 120-127 are reversed for system stuff (all notes off, etc)

where are you seeing this 95 limit?
I though I changed it to 120 already..

**Comment by sonejostudios** [comment]
in the gui (parameters). 
carla version 1.2.4

what about all the reserved parameter? are they used by carla or is it just a GM convention thing?
If it is just a convention thing is there a way to bypass it? My Controler (Novation LaunchControlXL) has knob already set to reserved cc (i.e 32) an I would prefer to keep it like this (factory reset). If it is not possible to bypass reserved ccs I will change them.

**Comment by falkTX** [comment]
ah you're using the old 1.x series.

this (and a lot of other stuff) has been fixed already in the 2.x series.
The 2.x series are currently in beta, but it's mostly because of some unfinished features (plugin bridges and skins)

about CCs, there's an lv2 plugin by Robin Gareus that allows to remap CCs.

**Comment by sonejostudios** [comment]
is carla 2 already in your repo? is it the one called carla-git?

**Comment by falkTX** [comment]
Yes, the carla-git package is the one that provides the latest version.
I update it quite often. :)
