### ISSUE TITLE
[Feature Request] monitor jack connections

### ISSUE THREAD

**Issue by IARI** [falkTX/Carla#287]
From what I understand at present carla establishes jack connections saved in the project when
- the project file is opened

Assume carla is running with a project opened. Consider the following features:
- [ ] a button that triggers the establish-connection actions performed on open-project
- [ ] an option to have it surveil the connections continuousely.

To have at least one of those would be very neat. :+1:

**Comment by falkTX** [comment]
Even though I understand the idea behind this, I am going to close this as "won't fix".
Carla has some session-manager functionality due to saving&restoring connections, but it is mostly about itself and not so much about storing connections of external clients.

For managing external applications, their state and their connections, better to go with a fully-fledged SM.
Me and a few other people are focusing our efforts into NSM.
