### ISSUE TITLE
Carla's ZynAddSubFX lv2 lags in Ardour 4.2

### ISSUE THREAD

**Issue by a-parhom** [falkTX/Carla#294]
When using Carla in Ardour 4.2 included ZynAddSubFX plugin becomes unusable: UI is very slow and the sound comes with huge delay. Other lv2 plugins and instruments in the same Ardour session work fine with no lags. I used the latest carla-git package from kxstudio ppa.

**Comment by falkTX** [comment]
This is a "known" issue with the zyn plugin, it's not splitting the MIDI events for processing because Carla usually does that.
When running in other hosts this was not very noticeable because of small buffer sizes.

With ardour4.2 all lv2 plugins run at a theoric 8192 buffer size (reported via maxBlockLength).
I'll implement a process split into zyn which should solve this..
