### ISSUE TITLE
Save and restore node arrangement in carxp file

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#349]
When I create a Carla project I use the area to place nodes in such a way that they are self-expliantory.

However frequently when I load the project I see that Carla arranges my nodes differently, which makes it harder to work with the project as I need to search for the right nodes, and can't just grab them instantly.

I think it's a pretty basic thing, I don't see any posision information in carxp files, should something like this (PosX, and PosY items):

```
<Plugin>
<Info>
<Type>INTERNAL</Type>
<Name>MIDI Through</Name>
<Label>midithrough</Label>
<PosX>324</PosX>
<PosY>1023</PosY>
</Info>
```

**Comment by falkTX** [comment]
this is something that needs to be implemented sooner or later.
we can't just position the plugins though, other jack clients need to be positioned as well as we might have connections to them.

**Comment by falkTX** [comment]
A temporary/experimental way to save this has been added, seamless to the user.
I did not decide on the final format yet though, so it's subject to change.
But since we did not had it implemented before, if I change the format later we don't lose too much...
Though it's likely to stay as it is for the entire life of Carla v2.x
