### ISSUE TITLE
Feature Request: Expose internal parameters

### ISSUE THREAD

**Issue by progwolff** [falkTX/Carla#424]
When using carla as a plugin, would it be possible to let carla expose the parameters of the plugins loaded inside carla?
This would allow using the MIDI learn features of the DAW carla is loaded in and for many use cases solve #26 .

**Comment by falkTX** [comment]
My idea is have 100 generic parameters exposed in the carla-plugin,
then inside carla allow to map them to any plugin parameter that is automable.

Needs a new (plugin version only) window.

**Comment by CG-3D** [comment]
I would love to be able to route external parameters to the internal plugin parameters in Carla (Patchbay). Is this feature still in development?

**Comment by falkTX** [comment]
latest develop branch now exposes the first plugin parameters to carla-vst plugin.
should be enough for a test to see if it works well or not.

**Comment by alfonso73** [comment]
> My idea is have 100 generic parameters exposed in the carla-plugin,
> then inside carla allow to map them to any plugin parameter that is automable.
> 
> Needs a new (plugin version only) window.

I would do something like 256 or 512 free assignable parameters.

**Comment by fonkle** [comment]
First n parameters show up and work on Carla Rack inside Bitwig Studio Linux. When modulated, the knobs on the Carla Rack move as expected, but the knob / parameter of the instrument (VST) is not modulated.

It would be cool if this would work with all parameters. It seems slightly slower to open an instrument now though...?

For use in Bitwig Studio, they wouldn't even have to show up on the rack, because it will show the last knob touched in the BS interface, so it can be modulated.

**Comment by falkTX** [comment]
I am closing this issue since parameters are exposed in v2.1
If there are issues with it, they should go into their own separate tickets.
