### ISSUE TITLE
Styles not found during make install

### ISSUE THREAD

**Issue by cocreature** [falkTX/Carla#447]
I was trying to update the Arch PKGBUILD but I’m running into
```
# Install theme
install -m 644 \
	bin/styles/* \
	/home/moritz/code/pkgbuilds/carla-git/pkg/carla-git//usr/lib/carla/styles
install: cannot stat 'bin/styles/*': No such file or directory
```
https://github.com/falkTX/Carla/commit/3075aa2c453593a19520ed07bd07aa4a549a193f might be related but I haven’t tracked down yet which commit broke the build for me.

**Comment by falkTX** [comment]
Did you change the DEFAULT_QT during make? (Building).
The building needs to match the install one.


On Jan 6, 2017 07:59, "Moritz Kiefer" <notifications@github.com> wrote:

I was trying to update the Arch PKGBUILD but I’m running into

# Install theme
install -m 644 \
	bin/styles/* \
	/home/moritz/code/pkgbuilds/carla-git/pkg/carla-git//usr/lib/carla/styles
install: cannot stat 'bin/styles/*': No such file or directory

3075aa2
<https://github.com/falkTX/Carla/commit/3075aa2c453593a19520ed07bd07aa4a549a193f>
might be related but I haven’t tracked down yet which commit broke the
build for me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/falkTX/Carla/issues/447>, or mute the thread

**Comment by cocreature** [comment]
Ah thanks
