### ISSUE TITLE
Maximizing Carla patchbay Lv2 GUI?

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#508]
I'm trying out using Carla Patchbay Lv2 in Ardour as a synth.

The biggest problem I see right now is that the window is rather small and there's not much space to work in:
![spectacle fb3627](https://user-images.githubusercontent.com/491704/29753182-19f687c8-8b6c-11e7-990c-f14b3b613279.png)

I know Helm 0.9.0 is able to change the size of it's window to some extent, so maybe it is possible somehow?

If I could just maximize it - that'd be perfect.
Or maybe I can connect with another Carla via OSC to configure the Patchbay remotely that way?

**Comment by falkTX** [comment]
You can remove the X11 embed UI from the ttl files, and then it gets resizable (because carla itself provides the window, not ardour). But on the other hand, you lose ardour controls (presets, bypass, etc)

I want to make the window resizable in the future as well, but it's not a priority at this point.

**Comment by unfa** [comment]
That hack seems like a nice option!

**Comment by falkTX** [comment]
I am closing this issue, in favour of #693.
Target will be to display a tiny plugin UI that simple has a button to open the full one.
When we embed we lose drag&drop in some hosts, and keyboard shortcuts on all of them.
Plus resizing gets really tricky, and embed itself as well...
I will stop trying to make Qt embed into something else, that is not going to work well long term.
