### ISSUE TITLE
Carla ligtweight edition?

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#528]
Hi!

Carla comes with its own embedded version of plugins like ZynAddSubFX, Nekobi or REV1 to name a few. These are already available in the KXStudio repositories and I don't know if it is possible/desirable but would it be possible to ship Carla (or make it a compile flag) without these so to not have multiple versions of the same plugin?
There is a logical reason to embed them in Carla and I suppose it is related to the win and mac ports but isn't this design decision ultimately against the philosophy of a rack, that is to provide an empty, lightweight but sturdy frame to connect them all?
I can live with it by unticking the "internal" box or looking at the authors in Ardour but I'm concerned about the maintainability (and the memory footprint maybe?) on the long term and your increasing work charge (congrats for the job in Germany by the way!) hence this philosophical discussion here :)

Anyway, thanks again! :)
Barbouze

**Comment by falkTX** [comment]
This was already my thought.
If you look at the recent branches, you'll see:
https://github.com/falkTX/Carla/tree/no-juce -> removing juce from the source code
https://github.com/falkTX/Carla/tree/external-plugins  -> moving non-essential internal plugins into a separate folder, so that eventually they go into a separate git repo.

Those plugins take no effort to maintain when they're inside carla by the way.
But I can see how it could make carla appear bloated.

Carla is going through a very hard stripping down of features right now, because of the removal of juce.
We'll lose a bunch of stuff used in win/mac (vst3, au, juce audio dev classes) and also the internal patchbay processing mode...
but I don't want to use juce anymore. I'll be posting some news about this very soon

**Comment by Barbouze** [comment]
Thanks a lot for those insider infos, I'll wait for the news :)
