### ISSUE TITLE
Linuxsampler crashing

### ISSUE THREAD

**Issue by Quirq-UK** [falkTX/Carla#550]
For some time I've been unable to load .gig files in Carla, every time I try I get the error:

"Failed to load plugin. Timeout while waiting for a response from plugin-bridge (or the plugin crashed on initialization?)"

Now when I try loading .gig files directly in LS/Qsampler (2:2.0.0+svn3347-1kxstudio2) I notice it crashes every time I try to load an instrument, with the message: "Could not get current list of channels. Sorry."

Does this need reporting upstream to the LS people?

**Comment by falkTX** [comment]
Don't report bugs upstream just yet as linuxsampler v2.0.0 was released recently and I'm yet to update to it, so issues might be fixed there.
I think the failure to load might be due to a refresh-plugins being needed after the latest changes.
Give it a try, refresh the entire plugin list including gig files, and see if it makes any different.
Also, see if you can drag&drop gig files into carla rack window.
Thanks

**Comment by Quirq-UK** [comment]
Brilliant, having refreshed the plugin list, Carla now loads .gig files :-) Dragging and dropping doesn't seem to work though.

I'm still getting the channels error message in LS though. Does that need a plugin refresh? If so, how do you do that in Qsampler?

**Comment by falkTX** [comment]
haha, the error you got before was just an internal carla thing.
QSampler doesn't store things in cache, so there's nothing to refresh.
For this you have to wait till I update the LS packages and see if the bug is still there or not.

Drag&drop works for me, but this depends on quite a few things on linux.
Double-clicking on the built-in carla's file browser panel should always work.

**Comment by Quirq-UK** [comment]
Ah, so two separate issues: Carla needing a refresh following changes and LS having its own weirdness!

Lack of drag and drop doesn't bother me, I always navigate through the Add Plugin dialog and open from there.

To be honest, I tend not to use LS/QS itself these days, I find Carla much more convenient, everything in one place and an easy-to-use plugin for Ardour.

Do you want me to close this, or wait till you've updated LS and see whether that fixes the LS issues?

**Comment by falkTX** [comment]
I think we close this, then since the QSampler issue is not related to Carla you can put it under https://github.com/KXStudio/Repository/issues.
I'll add a note to beta6-todo-list to bump the database file so old stuff gets ignored.
