### ISSUE TITLE
controls seem to "vibrate"

### ISSUE THREAD

**Issue by brummer10** [falkTX/Carla#553]
Hi

I notice a issue with gtk based plugins and 
carla -> settings -> use custom plugin slot skins 

when  use custom plugin slot skins  is enabled, the controls seem to vibrate (the knobs).
This happen with all GxPlugins and all guitarix plugins. 
when use custom plugin slot skins  is disabled, all plugs behave normal.

regards
hermann

**Comment by falkTX** [comment]
I've noticed this too, on some plugins.
It's not only guitarix stuff. There is a feedback loop of old/new value going on.

I have a feeling this is caused by 6426383aee95cdf3fcab9e13ee5b2d4f4129bd8d

**Comment by brummer10** [comment]
Okay, I do some debugging on this issue and found that if I block the write function, in the plugin UI, when the value was set from the host (port_event)  the feedback loop stops. 

I guess you'll like to implement something similar to that, so that you ain't inform the UI about a value change which was instantiated from the plugin UI.

**Comment by falkTX** [comment]
hmm so you're saying guitarix plugins, when they receive a parameter change from the host, they send back the same value back to the host?
regardless of carla bugs, this doesn't seem like a good thing for guitarix to do.
since the host sent that change to your UI, it already knows about the value.
this can create issues if a parameter is automated and changes often. (UI updates slower than DSP)

the same is true about carla. when it receives a parameter change from the UI, it should not send the same message back to the UI.
we can avoid the feedback loop on both sides.

**Comment by brummer10** [comment]
Yes, I'll implement the block for that case in the guitarix plugs.
