### ISSUE TITLE
Midi Through, Project and State

### ISSUE THREAD

**Issue by mbutz** [falkTX/Carla#626]
Hi,

I have some questions but I can't find any ansers on the official webpage or via Google (I am using version 1.9.8, 2.0beta6) on Linux Mint 18.1).

What I would like to do: Use Carla to have a setup integrating:

- Arturia Minilab as Midi-keyboard
- [Sonic Pi](https://github.com/samaaron/sonic-pi)
- Some plugins (especially softsynths like `Fluidsynth`)

I am trying to figure out how I can load all components and wire them accordingly possibly in one step via `carla`. I have a batch script starting `jack`, `carla` and `SonicPi`.

So here are my questions:

I see that you can save a carla project and load it with calling `carla` on the command line while providing a path to the `carxp` file. This does work with two issues

- It does not load the plugin configuration. For that - as I understand - the `carxs` file is responsible. So how can I load both files on startup?
- My `carla` project file does reestablish the patching but as I do not see `Midi Through` on `carla`s patchbay I have to manually connect `Midi Through` with `a2jmidi_bridge` via `qjackctl` connections. Is there a way to show `Midi Through` on `carla`s patchbay?

I would be very grateful for any hints into the right direction.

**Comment by Rippert** [comment]
I don't have your problem for the first question. When I load a carxp file at startup, my plugin's configurations are restored from when I saved the set-up. I am using the ALSA driver, instead of running through Jack, not sure if that matters. Check whether the Canvas menu has a choice of Internal or External. It does in ALSA mode, and you need to select External to see and connect ALSA MIDI ports to Carla.

For your second question, you might try to add some lines to your batch script that invoke the jack_connect program after Jack and Carla are started. jack_connect is a command line utility to connect Jack ports. jack_disconnect is it's opposite. you may need to start Jack with the `-X seq` option AFTER the `-d alsa` option. Or you could run `a2jmidid -e` after Jack starts instead of the `-X seq` option. Either way, you would initially use the jack_lsp utility, probably as `jack_lsp -A`, to get the names of the ports to use with jack_connect.

You could also try turning on Experimental Options and then turning on the ability to load Jack applications inside Carla as plugins. This would use the ALSA driver for Carla. Then wire everything up in Carla's patchbay. I do this, and it does save all the connections, however I don't use MIDI with any of the loaded Jack Apps. So I'm not sure if there are additional complications there.

**Comment by SpotlightKid** [comment]
> For your second question, you might try to add some lines to your batch script that invoke the jack_connect program after Jack and Carla are started.

You may also want to check out [jack-matchmaker](https://github.com/SpotlightKid/jack-matchmaker), [jack-autoconnect](https://github.com/kripton/jack_autoconnect), [aj-snapshot](http://aj-snapshot.sourceforge.net/) or [jack-plumbing](http://rd.slavepianos.org/sw/rju/md/jack-plumbing.md).

**Comment by mbutz** [comment]
Hi,

thanks a lot for the feedback on this! I will have to check this out. Seems to be a lot of options available.

**Comment by mbutz** [comment]
I got a bit further concerning the connections using `qjackctl`. If that does not work, I'll check out the other options you mentioned. Thanks again for this extensive list!

But I could not resolve the first issue:

Once `carla` has been started I can load my `carxp` file without any problem via the GUI. What seems not to be able is to load this file via command line ...

```
carla $HOME/my/path/to/config.carxp
```

... this launches `carla` with no project file loaded. I checked with `man carla` and `carla --help` if there is some option I need like e. g. `qjackctl` does, but there is no man or help entry available.

This is the same problem as described here: https://linuxmusicians.com/viewtopic.php?t=16146
Quote: "Unfortunately, that just opens up Carla, but it doesn't load the .carxp file."

**Comment by Rippert** [comment]
@mbutz - how are you entering your .carxp path? I have found that you have to use a path like you would to start a local script.

So I have the file `mycarla.carxp` inside a folder called `CarlaPresets`, inside my home folder. If my present working directory is my home folder, I have to type:

`carla ./CarlaPresets/mycarla.carxp`

That works. The more standard path:

`carla CarlaPresets/mycarla.carxp`

does not work.

-Ted

**Comment by mbutz** [comment]
Hi Ted,

thanks a lot. You made me thinking of what I actually did. A very silly mistake: I have my carla installation in $HOME/bin and made a shell script with which I called $HOME/bin/carla2/source/carla just by typing `carla`. Obviously this script does not accept any parameter (like the path to the carxp-file). So now I am calling `carla` directly from my audio setup script and - of course - it works. Thanks again and I'll close this ticket.
