### ISSUE TITLE
Update to fluidsynth 2.0

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#758]
See http://www.fluidsynth.org/api/index.html#NewIn2_0_0

**Comment by dvzrv** [comment]
I just tried to built carla with fluidsynth 2.0. It fails though:
[carla-1.9.11-fluidsynth2.0.0.txt](https://github.com/falkTX/Carla/files/2434843/carla-1.9.11-fluidsynth2.0.0.txt)

I'd be very happy if you would consider integrating this earlier than 2.1, if time permits.
Not sure how to package this otherwise... lots of breakage :(

**Comment by falkTX** [comment]
The change is already there in 2.0-RC2. Do you have an issue building that version?
