### ISSUE TITLE
Are plugins supposed to be double?

### ISSUE THREAD

**Issue by Jacalz** [falkTX/Carla#891]
All plugins seem to appear twice, are they supposed to be like that?
![image](https://user-images.githubusercontent.com/25466657/59972431-562a8580-958f-11e9-8b62-206a80d765e6.png)

And while at it, how would I build Carla with external plugins? It comes up as big no during build time but I can't find any info on how to do it.

**Comment by falkTX** [comment]
Yes, they appear as double because one is the internal plugin version, and the other is the LV2 version.

To build external plugins you simply have to enable git submodules before the build.
I don't recommend to do that though, as all external plugins are available in other formats (LV2 and VST), and specially not recommended for distribution packages as for them it is even more pointless (just add some plugins as required dependencies which does the same)

**Comment by Jacalz** [comment]
Thanks for the info 👍
