### ISSUE TITLE
CC scale plugin (by X42) skips steps when used in Carla

### ISSUE THREAD

**Issue by thijz** [falkTX/Carla#899]
The short version : 
When you use the 'Midi scale CC value' plugin (by X42 aka Robin Gareus) it 'skips' steps
The long version can be found here : https://github.com/x42/midifilter.lv2/issues/21

The plugin is supposed to translate incoming midi CC values ranging from 0 to 16 to 0-128 (= multiply by 8) but running in Carla it skips steps.
Really weird ...

running Carla v 2.0.0

**Comment by x42** [comment]
Can you also reproduce this with only the midifilter in Carla (no other clients)?

The suspicion would be that some shared jack/LV2 MIDI buffer is overwritten by other clients in the graph and the midifilter receives wrong input.

I did a quick test  jack-midi CC generator -> Carla  w/ scaleCC -> `jack_midi_dump` and cannot reproduce this issue.  That is with Carla  fe8d5e0072e9d from the develop branch.

The debug-print patch linked from https://github.com/x42/midifilter.lv2/issues/21#issuecomment-510518510 may still be helpful to track this down (print what scaleCC actually receives)

**Comment by thijz** [comment]
tested with the absolute minimum and i still see the same issue
where can i find the CC generator ?

**Comment by x42** [comment]
> where can i find the CC generator ?

I've used https://github.com/x42/mididebug.lv2 in jalv

**Comment by falkTX** [comment]
If you can upload here a project file that reproduces the issue, it would be very welcome.

**Comment by x42** [comment]
On 7/12/19 1:46 PM, Filipe Coelho wrote:
> If you can upload here a project file that reproduces the issue, it would be very welcome.

The main work here to add a MIDI generator that sends a CC message, and
attach a MIDI Monitor to show how it fails.

Inside Carla it's only

1) Start Carla
2) Load "MIDI Scale CC Value"
3) Edit the plugin, enable sending CCs to it
4) Set the plugin's "Value Scale" to 8.0

Now send `0xBF 0x01 0x09` to the plugin (CC channel 16, param 1 value 9)
and expect value (9 * 8) = 72 = 0x48 in return.

The output should show `0xBF 0x01 0x48`.

That works here, but on thijs machine it results in `0xBF 0x01 0x40`.

The only explanation I have is that scale2CC already receives incorrect
value input.

Even though the source is `0xBF 0x01 0x09`, the plugin receives `0xBF
0x01 0x08`. http://paste.debian.net/1091341/ can help to track this down.

It only affect certain values: 8 is sent instead of 9; and 12 is sent
instead of 13. This smells like a rounding issues, perhaps due to some
Carla remote-control or CC bindings or plugin bridges?!

Does the Carla project file include those preferences?

**Comment by thijz** [comment]
just recreated the setup on a different laptop (where i usually dont do any music stuff on)
using carla 2.0.0 and VMPK (virtual midi piano keyboard) and i get the exact same result 
this is really wierd ...
![image](https://user-images.githubusercontent.com/1384210/61152143-ec473100-a4e7-11e9-9670-45925e2e1ee9.png)

**Comment by x42** [comment]
I think @falkTX meant a carla session file (.carxp)

**Comment by thijz** [comment]
sure, here it is, but there really isnt much to it ... 

![image](https://user-images.githubusercontent.com/1384210/61152646-4d233900-a4e9-11e9-9062-c66c128a1e8a.png)


[CCscaling.zip](https://github.com/falkTX/Carla/files/3387727/CCscaling.zip)

note that this is the project file from my 'other' laptop
