### ISSUE TITLE
Simpler way to build windows bridge

### ISSUE THREAD

**Issue by Jacalz** [falkTX/Carla#918]
Building in multiple steps using minGW is cery complicated and it would be great if it could be done porely with wine instead if possible, without needing to use minGW. While the goal is a bit different, https://github.com/osxmidi/LinVst are letting windows and mac users load windows plugins without any need for a mingw toolchain which is wonderful. Lmms are also doing the same thing with their Wine incorporation in to the vestige plugin. Would this be possible to do with Carla too?

**Comment by falkTX** [comment]
Perhaps, but I have no interest on pursuing this.
It is intentional that carla uses mingw, so that the binaries it creates are real ones (they will run on Windows as-is) instead of using libwine.
wine-gcc is only needed for the bridge stuff between Linux and Windows.
This is increases the stability of the application A LOT.

Most distros nowadays have mingw in their repos, and a good enough/recent version at that.

So, while you can try to go into this target, I dont recommend it and will not support it from my side.
If you make changes in Carla in order to support this, I will be happy for review them.
