### ISSUE TITLE
Checkbox filters to require "Inline display" and "CV" in "Add Plugin" dialog?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#936]
Both of these filter options would make finding these types of plugin easier for users and spur developers to embrace these features.

**Comment by falkTX** [comment]
I agree for CV. I am going to see if I can add some quick utilities to carla's internal plugins, as not everyone will have ingen or mod-cv-plugins (unreleased for now) in order to make it actually useful.

inline displays, I am not sure if I would push for that.
it is nice, but consumes quite some cpu (due to python->c->python calls and data conversions).
though I have been wondering about auto-generation of screenshots and have them as inline-display for plugins that do not support it.
as long as it is labelled experimental, I guess we are mostly okay..
